# Generated by Django 3.1.4 on 2020-12-22 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('contest', '0001_initial'),
        ('question', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('score', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('IN_QUEUE', 'In Queue'), ('AC', 'Accepted'), ('PA', 'Partially Accepted'), ('CE', 'Compilation Error'), ('IE', 'Internal Error'), ('WA', 'Anything else')], default='IN_QUEUE', max_length=32)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.contest')),
                ('lang_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.language')),
                ('ques_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.question')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Verdict',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('IN_QUEUE', 'In Queue'), ('PROCESSING', 'Processing'), ('AC', 'Accepted'), ('WA', 'Wrong Answer'), ('TLE', 'Time Limit Exceeded'), ('CE', 'Compilation Error'), ('SIGSEGV', 'Runtime Error (SIGSEGV)'), ('SIGXFSZ', 'Runtime Error (SIGXFSZ)'), ('SIGFPE', 'Runtime Error (SIGFPE)'), ('SIGABRT', 'Runtime Error (SIGABRT)'), ('RTE', 'Runtime Error (other)'), ('NZEC', 'Runtime Error (NZEC)'), ('IE', 'Internal Error'), ('EFE', 'Exec Format Error')], default='IN_QUEUE', max_length=32)),
                ('stdout', models.TextField(blank=True, null=True)),
                ('stderr', models.TextField(blank=True, null=True)),
                ('exec_time', models.CharField(max_length=10, null=True)),
                ('mem', models.CharField(max_length=10, null=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verdicts', to='submission.submission')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.testcase')),
            ],
        ),
        migrations.CreateModel(
            name='RunSubmission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.TextField()),
                ('status', models.CharField(choices=[('IN_QUEUE', 'In Queue'), ('PROCESSING', 'Processing'), ('AC', 'Accepted'), ('WA', 'Wrong Answer'), ('TLE', 'Time Limit Exceeded'), ('CE', 'Compilation Error'), ('SIGSEGV', 'Runtime Error (SIGSEGV)'), ('SIGXFSZ', 'Runtime Error (SIGXFSZ)'), ('SIGFPE', 'Runtime Error (SIGFPE)'), ('SIGABRT', 'Runtime Error (SIGABRT)'), ('RTE', 'Runtime Error (other)'), ('NZEC', 'Runtime Error (NZEC)'), ('IE', 'Internal Error'), ('EFE', 'Exec Format Error')], default='IN_QUEUE', max_length=32)),
                ('stdin', models.TextField(blank=True)),
                ('stdout', models.TextField(blank=True, null=True)),
                ('stderr', models.TextField(blank=True, null=True)),
                ('exec_time', models.CharField(max_length=10, null=True)),
                ('mem', models.CharField(max_length=10, null=True)),
                ('lang_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.language')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
