# Generated by Django 3.1.14 on 2022-09-28 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HackSubmission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('correct_code_submission_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correct_code_submission', to='submission.runsubmission')),
                ('incorrect_code_submission_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incorrect_code_submission', to='submission.runsubmission')),
            ],
        ),
    ]
