# Generated by Django 3.1.14 on 2022-09-29 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0002_hacksubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='hacksubmission',
            name='status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('SUCCESS', 'Hack Successful'), ('FAILURE', 'Hack Unsuccessful')], default='PENDING', max_length=32),
        ),
    ]
