# Generated by Django 3.1.14 on 2022-10-16 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0006_auto_20220924_2242'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('question', '0008_auto_20220927_2316'),
        ('submission', '0003_hacksubmission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='hacksubmission',
            name='contest_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contest.contest'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hacksubmission',
            name='ques_id',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='question.question'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hacksubmission',
            name='user_id',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
