# Generated by Django 3.1.3 on 2020-11-10 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True,
                                        serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('score', models.IntegerField()),
                ('contest_id',
                 models.ForeignKey(null=True,
                                   on_delete=django.db.models.deletion.SET_NULL,
                                   to='contest.contest')),
            ],
        ),
    ]
