# Generated by Django 3.1.3 on 2020-11-10 21:10

import martor.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='description',
            field=martor.models.MartorField(default='ldkrjlrkt'),
            preserve_default=False,
        ),
    ]
