# Generated by Django 3.1.4 on 2020-12-30 07:33

from django.db import migrations, models
import question.models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='input',
            field=models.FileField(upload_to=question.models.upload_input_rename, validators=[question.models.validate_testcase]),
        ),
    ]
