# Generated by Django 3.1.3 on 2020-11-10 21:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('question', '0002_question_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.TextField(),
        ),
    ]
