# Generated by Django 3.1.14 on 2022-09-24 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201230_1303'),
        ('question', '0002_auto_20201230_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='hacking_incorrect_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='hacking_incorrect_code_lang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hacking_incorrect_lang', to='core.language'),
        ),
    ]
