# Generated by Django 3.1.14 on 2022-09-24 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201230_1303'),
        ('question', '0004_auto_20220924_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='HackingQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_code', models.TextField(blank=True, null=True)),
                ('incorrect_code', models.TextField(blank=True, null=True)),
                ('correct_code_lang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correct_code_lang', to='core.language')),
                ('fk_qid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.question')),
                ('incorrect_code_lang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incorrect_code_lang', to='core.language')),
            ],
        ),
    ]
