# Generated by Django 3.1.14 on 2022-09-24 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201230_1303'),
        ('question', '0005_hackingquestion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HackingQuestion',
            new_name='HackingCodes',
        ),
    ]
