# Generated by Django 3.1.14 on 2022-09-27 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201230_1303'),
        ('question', '0007_auto_20220924_2303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hackingcode',
            old_name='fk_qid',
            new_name='question',
        ),
        migrations.RemoveField(
            model_name='hackingcode',
            name='correct_code_lang',
        ),
        migrations.RemoveField(
            model_name='hackingcode',
            name='incorrect_code_lang',
        ),
        migrations.AddField(
            model_name='hackingcode',
            name='code_lang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='code_lang', to='core.language'),
        ),
    ]
