#Configuring TravisCI for the project
language: python
python:
  - "3.8"
dist: focal
services:
  - docker

before_script: pip install docker-compose

script:
  - docker-compose run --rm app sh -c "python manage.py test && flake8"