version: '3'

x-logging:
  &default-logging
  logging:
    driver: json-file
    options:
      max-size: 100m

services:
  server:
    image: judge0/judge0:latest
    volumes:
      - ./judge0.env:/judge0.env:ro
    ports:
      - "80:3000"
    privileged: true
    <<: *default-logging
    restart: always

  workers:
    image: judge0/judge0:latest
    command: [ "./scripts/workers" ]
    volumes:
      - ./judge0.env:/judge0.env:ro
    privileged: true
    <<: *default-logging
    restart: always

  db:
    image: postgres:alpine
    env_file: judge0.env
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    <<: *default-logging
    restart: always

  redis:
    image: redis:alpine
    command: [
        "bash", "-c",
        'docker-entrypoint.sh --appendonly yes --requirepass "$$REDIS_PASSWORD"'
    ]
    env_file: judge0.env
    volumes:
      - redis-data:/data
    <<: *default-logging
    restart: always

volumes:
  postgres-data:
  redis-data: