version: '3'

services:
  judge0:
    image: judge0/judge0:latest
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    ports:
      - "5000:3000"
    privileged: true
    restart: always

  workers:
    image: judge0/judge0:latest
    command: [ "./scripts/workers" ]
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    privileged: true
    restart: always

  db:
    image: postgres:alpine
    env_file: judge0.conf
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    restart: always

  redis:
    image: redis:alpine
    command: [
        "sh", "-c",
        'docker-entrypoint.sh --appendonly yes --requirepass "$$REDIS_PASSWORD"'
    ]
    env_file: judge0.conf
    volumes:
      - redis-data:/data
    restart: always

volumes:
  postgres-data:
  redis-data: