version: "3"
services:
  app: &app
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"

    command: >
      sh -c " python manage.py wait_for_db &&
              python manage.py makemigrations core contest question submission &&
              python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db-django
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=postgres
      - JUDGE0_BASE_URL=http://172.17.0.1:3000
      - JUDGE0_RUN_CALLBACK_URL=http://172.17.0.1:8000/run/callback
      - JUDGE0_SUBMIT_CALLBACK_URL=http://172.17.0.1:8000/submit/callback
    env_file:
      - .env
    depends_on:
      - db-django

  db-django:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
