# Generated by Django 3.1.3 on 2020-11-10 20:50

import martor.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True,
                                        serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('instructions', martor.models.MartorField()),
            ],
        ),
    ]
