# Generated by Django 3.1.3 on 2020-11-10 21:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='instructions',
            field=models.TextField(),
        ),
    ]
