# Generated by Django 3.1.14 on 2022-09-24 17:12

import contest.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0005_auto_20220922_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestque',
            name='is_hacking',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contest',
            name='banner_image',
            field=models.FileField(blank=True, null=True, upload_to=contest.models.upload_contest_banner),
        ),
    ]
