# Generated by Django 3.1.4 on 2020-12-22 07:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('judge0_lang_id', models.CharField(max_length=3)),
                ('stack_limit', models.IntegerField()),
                ('cpu_time_limit', models.IntegerField()),
                ('mem_limit', models.IntegerField(validators=[django.core.validators.MinValueValidator(2048)])),
                ('filesize_limit', models.IntegerField()),
                ('process_limit', models.IntegerField()),
                ('wall_time_limit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserContest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('REGISTERED', 'REGISTERED'), ('STARTED', 'STARTED'), ('ENDED', 'ENDED')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penalty', models.FloatField(default=0)),
                ('score', models.FloatField(default=0)),
            ],
        ),
    ]
