# Generated by Django 3.1.4 on 2020-12-22 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contest', '0002_auto_20201222_1316'),
        ('core', '0001_initial'),
        ('question', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userquestion',
            name='que',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='question.question'),
        ),
        migrations.AddField(
            model_name='userquestion',
            name='user_contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.usercontest'),
        ),
        migrations.AddField(
            model_name='usercontest',
            name='contest_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.contest'),
        ),
        migrations.AddField(
            model_name='usercontest',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='userquestion',
            unique_together={('user_contest', 'que')},
        ),
        migrations.AddIndex(
            model_name='usercontest',
            index=models.Index(fields=['contest_id', 'user_id'], name='core_userco_contest_e7b866_idx'),
        ),
    ]
