# Generated by Django 3.1.4 on 2020-12-22 08:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201222_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='monaco_lang_code',
            field=models.CharField(default='cpp', max_length=20),
        ),
        migrations.AlterField(
            model_name='language',
            name='cpu_time_limit',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='language',
            name='filesize_limit',
            field=models.IntegerField(default=1024),
        ),
        migrations.AlterField(
            model_name='language',
            name='mem_limit',
            field=models.IntegerField(default=2048, validators=[django.core.validators.MinValueValidator(2048)]),
        ),
        migrations.AlterField(
            model_name='language',
            name='process_limit',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='language',
            name='stack_limit',
            field=models.IntegerField(default=2048),
        ),
        migrations.AlterField(
            model_name='language',
            name='wall_time_limit',
            field=models.IntegerField(default=3),
        ),
    ]
