# Generated by Django 3.1.4 on 2020-12-30 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0003_contest_banner_image'),
        ('core', '0003_auto_20201222_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontest',
            name='contest_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_contests', to='contest.contest'),
        ),
        migrations.AlterField(
            model_name='usercontest',
            name='status',
            field=models.CharField(choices=[('REGISTERED', 'REGISTERED'), ('STARTED', 'STARTED'), ('ENDED', 'ENDED')], default='REGISTERED', max_length=20),
        ),
    ]
